name: Testing
on: [pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - name: Test
        run: |
          echo "Starting Tests"
          cd opensearch-operator
          ls
          make test
